#!/usr/bin/env bash

#
# Copyright 2020 Alexander Vollschwitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Note: All variables defined in Makefile can be directly accessed here.
#

# shellcheck disable=SC2034
{
# formatting
BLD="\e[1m"
DIM="\e[2m"
ITL="\e[3m"
NRM="\e[0m"
OK="\e[01;32m"
ERR="\e[01;31m"
}

#
#
#
function synopsis {

	echo "hello"

    shopt -s extglob
    local file
    file="$(echo "${MAKEFILE_LIST##+([[:space:]])}" | cut -d ' ' -f 1)"

    echo -e "\n${BLD}TARGETS${NRM}"
    print_formatted_help "$(
        awk '{FS=":"}
            /^[-a-zA-Z0-9_]+:[-a-zA-Z0-9_ ]*$/{f=1; printf "\n${ITL}${BLD}%s${NRM}\n", $1; next}
            /^[^#].*$/{f=0} f' "${file}" \
         | tr -d '#')"

    echo -e "\n\n${BLD}NOTES${NRM}\n"
    print_formatted_help "$(
        awk '/^##$/{f=1; printf "-%s", $0; next} /^[^#].*$/{f=0} f' "${file}" \
         | tr -d '#')"
    echo
}

#
# $1	help text
#
function print_formatted_help {
    echo -e "$(apply_shell_expansion "$1")" | uniq
}

#
# $1	string to expand
#
function apply_shell_expansion {
    declare data="$1"
    declare delimiter="__apply_shell_expansion_delimiter__"
    declare command="cat <<${delimiter}"$'\n'"${data}"$'\n'"${delimiter}"
    eval "${command}"
}

#
#
#

"$@"
